# Generated by Django 5.0.7 on 2024-07-17 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='book',
        ),
    ]
